const data = {
  products: [
    {
      _id: "1",
      name: "Gamepad",
      category: "Videogames",
      image: "/images/product.jpg",
      price: 120,
      brand: "AMD",
      rating: 5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: "2",
      name: "Controller",
      category: "Videogames",
      image: "/images/product.jpg",
      price: 100,
      brand: "AMD",
      rating: 2,
      numReviews: 22,
      description: "High quality product",
    },
    {
      _id: "3",
      name: "Processor",
      category: "Videogames",
      image: "/images/product.jpg",
      price: 20,
      brand: "AMD",
      rating: 3,
      numReviews: 22,
      description: "High quality product",
    },
    {
      _id: "4",
      name: "Graphic",
      category: "Videogames",
      image: "/images/product.jpg",
      price: 180,
      brand: "AMD",
      rating: 4.5,
      numReviews: 17,
      description: "High quality product",
    },
    {
      _id: "5",
      name: "RAM",
      category: "Videogames",
      image: "/images/product.jpg",
      price: 75,
      brand: "AMD",
      rating: 5,
      numReviews: 8,
      description: "High quality product",
    },
  ],
};

export default data;
